name: Use custom-image-dev

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: custom-image-dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: node version
      run: node -v

    - name: az version
      run: az --version

    - name: az login
      run: az login --service-principal --tenant "${AZURE_TENANT_ID}" --username "${AZURE_CLIENT_ID}" --federated-token "$(cat ${AZURE_FEDERATED_TOKEN_FILE})"

    - name: az list all resources
      run: az resource list -o table
    
